# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SignalToSms < Formula
  desc "Decrypt and convert Signal for Android backups so they can be restored as SMSes that can be moved to iMessage on iPhones. NOT AFFILIATED WITH OR OFFICIALLY BLESSED BY SIGNAL."
  homepage "https://github.com/jamescostian/signal-to-sms"
  version "1.0.0"
  license "GPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jamescostian/signal-to-sms/releases/download/v1.0.0/signal-to-sms-1.0.0-macOS-x64.tar.gz"
      sha256 "f02e0fcb1b3ac7ec770655fbf869b128819795b00849c601810782f23dd08eb0"

      def install
        bin.install "signal-to-sms"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jamescostian/signal-to-sms/releases/download/v1.0.0/signal-to-sms-1.0.0-macOS-arm64.tar.gz"
      sha256 "6fb0762a6775f48dd3f13dd2555c5ff75a4335f2acf092402bbdd14fdad998a9"

      def install
        bin.install "signal-to-sms"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jamescostian/signal-to-sms/releases/download/v1.0.0/signal-to-sms-1.0.0-linux-x64.tar.gz"
      sha256 "5637cbf894eb5206d7a54644b72921fcaf23e8ea1a001d931ada997d3eb9d308"

      def install
        bin.install "signal-to-sms"
      end
    end
  end

  depends_on "sqlite"

  test do
    system "#{bin}/signal-to-sms -v"
  end
end
